hello world
hello world abcd
x = 5, six = 6
x - 5 y - 25, and negative numbers are -1, -2, -3
Preceding with blanks:          5
Preceding with zeros 0000000042 and different radices 52 2a 052 0x2a 

Floats: 8.73 +9e+00 1.230000E+00
Width:    42
Percent: 42%
Multiple percentage: % 8.73% %
Variable width     42
Variable precision     8.73   1.23 and   8.73%
Var is 22, x is 42 Now y is       25 and two is 2
eager =  123 999
hello world
number is 00042
heap print: world
no markers here
goodbye world
